openapi: 3.0.3
info:
  title: TGFlow Licensing API
  version: 0.1.0
servers:
  - url: http://localhost:8000
paths:
  /auth/login:
    post:
      tags: [auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                device_fingerprint:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id: { type: string }
                      email: { type: string, format: email }
        '401': { description: Invalid credentials }

  /license:
    get:
      tags: [license]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  plan: { type: string }
                  status: { type: string }
                  quota:
                    type: object
                    properties:
                      monthly_limit: { type: integer }
                      used: { type: integer }
                      remaining: { type: integer }
                      reset_at: { type: string, format: date-time }
                  device_binding:
                    type: object
                    properties:
                      device_fingerprint: { type: string, nullable: true }
        '401': { description: Unauthorized }

  /usage/reserve:
    post:
      tags: [usage]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                messages: { type: integer, minimum: 1 }
                correlation_id: { type: string, format: uuid }
              required: [messages, correlation_id]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  reservation_id: { type: string, format: uuid }
                  reserved: { type: integer }
                  remaining: { type: integer }
        '401': { description: Unauthorized }
        '402': { description: Insufficient quota }
        '409': { description: Idempotency conflict }
        '422': { description: Validation error }

  /usage/commit:
    post:
      tags: [usage]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reservation_id: { type: string, format: uuid }
                used: { type: integer, minimum: 0 }
              required: [reservation_id, used]
      responses:
        '200': { description: OK }
        '401': { description: Unauthorized }
        '402': { description: Insufficient quota }
        '409': { description: Already closed }
        '422': { description: Validation error / expired / not found }

  /usage/rollback:
    post:
      tags: [usage]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reservation_id: { type: string, format: uuid }
              required: [reservation_id]
      responses:
        '200': { description: OK }
        '401': { description: Unauthorized }
        '409': { description: Already closed }
        '422': { description: Not found }

  /plans:
    get:
      tags: [plans]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: { type: string, format: uuid }
                    name: { type: string }
                    price: { type: integer }
                    currency: { type: string }
                    monthly_limit: { type: integer }

  /.well-known/jwks.json:
    get:
      tags: [jwks]
      responses:
        '200':
          description: JWKS-like public key bundle
          content:
            application/json:
              schema:
                type: object
                properties:
                  keys:
                    type: array
                    items:
                      type: object
                      properties:
                        kty: { type: string }
                        alg: { type: string }
                        use: { type: string }
                        kid: { type: string }
                        pem: { type: string }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

openapi: 3.0.3
info:
  title: TGFlow Licensing & Usage API
  version: 0.1.0
servers:
  - url: https://api.dev.tgflow.local
    description: Local development server
paths:
  /auth/login:
    post:
      summary: Login and issue JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /license:
    get:
      summary: Get current license and quota
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicenseResponse'
  /usage/reserve:
    post:
      summary: Reserve quota for messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReserveRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReserveResponse'
  /usage/commit:
    post:
      summary: Commit used quota
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommitRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'
  /usage/rollback:
    post:
      summary: Rollback reservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RollbackRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'
  /plans:
    get:
      summary: List plans
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plan'
  /billing/checkout:
    post:
      summary: Create checkout session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckoutRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckoutResponse'
  /billing/webhook:
    post:
      summary: Billing provider webhook
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Ok:
      type: object
      properties:
        ok:
          type: boolean
    LoginRequest:
      type: object
      required: [email, password, device_fingerprint]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        device_fingerprint:
          type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
        user:
          $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        created_at:
          type: string
          format: date-time
    LicenseResponse:
      type: object
      properties:
        plan:
          $ref: '#/components/schemas/Plan'
        status:
          type: string
          enum: [active, past_due, canceled]
        quota:
          $ref: '#/components/schemas/Quota'
        device_binding:
          type: string
    Plan:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: number
          format: float
        currency:
          type: string
        monthly_limit:
          type: integer
    Quota:
      type: object
      properties:
        monthly_limit:
          type: integer
        used:
          type: integer
        remaining:
          type: integer
        reset_at:
          type: string
          format: date-time
    ReserveRequest:
      type: object
      required: [messages, correlation_id]
      properties:
        messages:
          type: integer
        correlation_id:
          type: string
    ReserveResponse:
      type: object
      properties:
        reservation_id:
          type: string
          format: uuid
        reserved:
          type: integer
        remaining:
          type: integer
    CommitRequest:
      type: object
      required: [reservation_id, used]
      properties:
        reservation_id:
          type: string
          format: uuid
        used:
          type: integer
    RollbackRequest:
      type: object
      required: [reservation_id]
      properties:
        reservation_id:
          type: string
          format: uuid
    CheckoutRequest:
      type: object
      required: [plan_id, return_url]
      properties:
        plan_id:
          type: string
          format: uuid
        return_url:
          type: string
          format: uri
    CheckoutResponse:
      type: object
      properties:
        checkout_url:
          type: string
          format: uri
security:
  - bearerAuth: []

